spring.application.name=paymentService


# Server port
server.port=8083

# JWT
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# PostgreSQL Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework=INFO
spring.main.log-startup-info=false
debug=false

spring.aop.proxy-target-class=true
spring.mvc.hiddenmethod.filter.enabled=true
spring.mvc.problemdetails.enabled=false
spring.jpa.open-in-view=false
notification-service.url=${USER_SERVICE}
user-service.url=${NOTIFICATION_SERVICE}

spring.main.allow-bean-definition-overriding=true